from colorama import Fore, Style
import time
import os

screenSize = os.get_terminal_size()
z = int(screenSize[0])

revolutions = int(input("How many revolutions should the code make?\n\n"))
x = revolutions
input("press enter to start while loop")
y = 0.05

while x > 0:
    x -= 1
    print(Style.BRIGHT + Fore.RED + "around the world around the world around the world around the world around the world around the world ".center(z))
    time.sleep(y)
    os.system('clear')
    print(" around the world around the world around the world around the world around the world around the world".center(z))
    time.sleep(y)
    os.system('clear')
    print(Fore.GREEN + "d around the world around the world around the world around the world around the world around the worl".center(z))
    time.sleep(y)
    os.system('clear')
    print("ld around the world around the world around the world around the world around the world around the wor".center(z))
    time.sleep(y)
    os.system('clear')
    print(Fore.MAGENTA + "rld around the world around the world around the world around the world around the world around the wo".center(z))
    time.sleep(y)
    os.system('clear')
    print("orld around the world around the world around the world around the world around the world around the w".center(z))
    time.sleep(y)
    os.system('clear')
    print(Fore.RED + "world around the world around the world around the world around the world around the world around the ".center(z))
    time.sleep(y)
    os.system('clear')
    print(" world around the world around the world around the world around the world around the world around the".center(z))
    time.sleep(y)
    os.system('clear')
    print(Fore.GREEN + "e world around the world around the world around the world around the world around the world around th".center(z))
    time.sleep(y)
    os.system('clear')
    print("he world around the world around the world around the world around the world around the world around t".center(z))
    time.sleep(y)
    os.system('clear')
    print(Fore.MAGENTA + "the world around the world around the world around the world around the world around the world around ".center(z))
    time.sleep(y)
    os.system('clear')
    print(" the world around the world around the world around the world around the world around the world around".center(z))
    time.sleep(y)
    os.system('clear')
    print(Fore.RED + "d the world around the world around the world around the world around the world around the world aroun".center(z))
    time.sleep(y)
    os.system('clear')
    print("nd the world around the world around the world around the world around the world around the world arou".center(z))
    time.sleep(y)
    os.system('clear')
    print(Fore.GREEN + "und the world around the world around the world around the world around the world around the world aro".center(z))
    time.sleep(y)
    os.system('clear')
    print("ound the world around the world around the world around the world around the world around the world ar".center(z))
    time.sleep(y)
    os.system('clear')
    print(Fore.MAGENTA + "round the world around the world around the world around the world around the world around the world a".center(z))
    time.sleep(y)
    os.system('clear')
    print("around the world around the world around the world around the world around the world around the world ".center(z))
    time.sleep(y)
    os.system('clear')
    #print(Fore.CYAN + "d the world around the world around the world around the wor".center(z))
    #time.sleep(y)
    #os.system('clear')
    #print("nd the world around the world around the world around the wo".center(z))
    #time.sleep(y)
    #os.system('clear')
    #print(Fore.BLUE + "und the world around the world around the world around the w".center(z))
    #time.sleep(y)
    #os.system('clear')
    #print("ound the world around the world around the world around the ".center(z))
    #time.sleep(y)
    #os.system('clear')
    #print(Fore.MAGENTA + "round the world around the world around the world around the".center(z))
    #time.sleep(y)
    #os.system('clear')
    #print("around the world around the world around the world around th".center(z))

